EXIT = 100
LOGOUT = 101
NUM_NEIGHBOURS = 15
# For user courses
EID_UIDX = 0
GRADE_UIDX = 1
CRANK_UIDX = 2
IRANK_UIDX = 3
CID_UIDX = 4
SEM_UIDX = 5
YR_UIDX = 6
STD_UIDX = 7
TOD_UIDX = 8
DEPT_UIDX = 9
CNUM_UIDX = 10
CNAME_UIDX = 11
# For regular courses
EID_CIDX = 0
CID_CIDX = 1
SEM_CIDX = 2
YR_CIDX = 3
STD_CIDX = 4
TOD_CIDX = 5
DEPT_CIDX = 6
CNUM_CIDX = 7
CNAME_CIDX = 8
# For topics
CID_TIDX = 0
EID_TIDX = 1
TID_TIDX = 2
INTB_TIDX = 3
INTA_TIDX = 4
TOPIC_TIDX = 5
DEPT_TIDX = 6
CNUM_TIDX = 7
# For skills
CID_SIDX = 0
EID_SIDX = 1
SID_SIDX = 2
SKB_SIDX = 3
SKA_SIDX = 4
SKILL_SIDX = 5
DEPT_SIDX = 6
CNUM_SIDX = 7

# list of letter grades
GRADES = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F"]
